export enum RecrutmentStatus {
    IN_REVIEW = "IN_REVIEW",
    PENDING_INTERVIEW = "PENDING_INTERVIEW",
    PROCESSING_INTERVIEW = "PROCESSING_INTERVIEW",
    INTERVIEW_SUCESSFUL = "INTERVIEW_SUCESSFUL",
    INTERVIEW_FAILED = "INTERVIEW_FAILED",
    JOB_OFFERED = "JOB_OFFERED",
    JOB_OFFERE_ACCEPTED = "JOB_OFFERE_ACCEPTED",
    JOB_OFFERE_REJECTED = "JOB_OFFERE_REJECTED",
    RECRUTED = "RECRUTED",

}